### PR TITLE
Abstract Logic for urls lighthouse-docker audits

### PR DESCRIPTION
**Pull request by ardelato**
## Description

This moves the urls to a json file with a particular structure, as stated in the urls.example.json file. This will allow us to easily configure the urls we want to audit and easily tag them when sending them to DataDog.

### CR

I chose to move the urls to a `json` file so it would make it easier to modify if the current list selected from minerva.ifixit.com would not be suitable for addressing https://github.com/iFixit/ifixit/issues/48916

### QA 

- [ ] Confirm `lighthouse-docker` audits the list of urls in `urls.json` and sends them to DataDog with the `page_type` value of the key.

Connects: https://github.com/iFixit/ifixit/issues/48916

### CODE REVIEW

**Review by mlahargou — COMMENTED** [review]
Where is the urls.json file?

**Comment by ardelato** [comment]
> Where is the urls.json file?

I was going to add it on the `server-templates` side so we could more easily modify it and have it close to where we configure `lighthouse-docker`. 

https://github.com/iFixit/server-templates/blob/9f41198e962b65868cdee09a40bd9048f255dcfb/ansible/playbooks/ci/launch-lighthouse-docker.yml

**Review by mlahargou — APPROVED** [review]
CR 📱

**Comment by deltuh-vee** [comment]
QA 🎬 
`lighthouse-docker` audits the list of urls in `urls.json` and still sends reports to Datadog.

**Pull request merged**
