### PR TITLE
Add additional Lighthouse-related tooling

### PR DESCRIPTION
**Pull request by andyg0808**
This is most of the tooling I regularly use with the Docker image built by this repo. Providing it here allows us to start to centralize all our Lighthouse-related tooling.

QA
---
~Please try following the README discussion on doing a performance analysis with the new `bin/run` script.~
qa_req 0

Since we're not planning to use most of this tooling, and I'm the primary user of the `run`/`R-docker`/`analysis.R` parts, I don't think it's worth the cost to QA.

### CODE REVIEW

**Review by djmetzle — APPROVED** [review]
Nice. Great work!
CR :gear:

**Comment by ardelato** [comment]
dev_block ☁️  there are still some bugs trying get this up and running out of the box.

<details>
	<summary>1. <code>/bin/lighthouse</code>'s logger needs to be modified </summary>

When trying to run ` bin/lighthouse . test https://www.ifixit.com` it kept failing because the variable `log` although defined and initialized outside the scope of `main`, the ruby script kept failing because it wasn't properly defined as a global variable.

I noticed that in `/bin/run` that logging object was defined using `Log = Logger.new($stderr)` instead of `log = Logger.new($stderr)`, so after changing `/bin/lighthouse` to match that declaration method, the script worked

</details>

<details>
	<summary>2. <code>analysis.r</code> needs to be updated to use correct paths </summary>

When opening `analysis.r` and running `setwd(~)` the working directory seems to be set to root directory of the repo, therefore when trying to run `devtools::install_local("./webperf/", upgrade="never")` it fails to find the directory `webperf` since it is not in root directory.

We can either prepend `./analysis/` to the paths of change the working directory to `~/analysis`

</details>

<details>
	<summary>3. Gem permission issues when running <code>./install.sh</code> </summary>

When I tried running the install script, it was failing to run `gem install docopt`. I am not sure if the install script needs its permissions changed to be able to run that line or if the command needs to be changed. 

However, I ran `./install.sh` with sudo and that worked.

Install Permissions error

</details>

---

Some minor issues:

<details>
	<summary>4. From a UI perspective, using <code><endpoint_name></code> for the output file name is confusing </summary>

When I first looked at the usage message for `/bin/lighthouse` I wasn't sure what `<endpoint_name>` was for until I ran the command and saw it was the name of the output file. 

Therefore, it was not intuitive in understand what  the `<endpoint_name>` argument was. 

</details>

<details>
	<summary>5. Using <code>--html</code> makes the script not fully respect <code><endpoint_name></code>  argument</summary>

If I ran the command `bin/lighthouse . test https://www.ifixit.com` I only got a json file named `test.json`. 

However, if I then added the `--html` flag, `bin/lighthouse --html . test https://www.ifixit.com` I got a json file and an html file with `test.report.` as the file name. 

Html flag comparison

</details>

<details>
	<summary>6. I think the README could be updated to reflect the steps a little better </summary>

```diff
diff --git a/README.md b/README.md
index 1c73e17..dfa9115 100644
--- a/README.md
+++ b/README.md
@@ -16,15 +16,15 @@ There are two scripts provided to gather Lighthouse results for URLs:
 ### Single Lighthouse run:
 Use the `lighthouse` script to run a single Lighthouse run against some URL:
 ```sh
-bin/lighthouse [--html] <output_directory> <endpoint_name> <URL>
+bin/lighthouse [--html] <output_directory> <output_filename> <URL>
 ```
 
 Pass in:
 - an output directory to put the result files into
-- a name for the endpoint to audit
+- a file name for the outputted audit
 - an URL
 
-This will emit the full Lighthouse report into the output directory and name it `<endpoint_name>.json`.
+This will emit the full Lighthouse report into the output directory and name it `<output_filename>.json`.
 
 Use the `--html` flag to emit the human-readable HTML report instead.
 
@@ -36,21 +36,26 @@ export PATH="$(readlink -e bin):$PATH"
 
 Use the `run` script to run a series of Lighthouse runs against a group of pages:
 ```sh
-mkdir -p analysis/results
-cd analysis/results
-run 'www=https://your-site.com' 'dev=https://your-dev-version:8000'
+lighthouse-docker > mkdir -p analysis/results
+lighthouse-docker > cd analysis/results
+lighthouse-docker/analysis/results > run 'www=https://your-site.com' 'dev=https://your-dev-version:8000'
 ```
 
 By default it runs three Lighthouse runs against each configuration (three against `your-site.com` and three against `your-dev-version:8000`) and outputs the results to sequentially-numbered JSON files prefixed with the configuration name (`www` and `dev` in this case, so we'd expect files named things like `www_1.json`, `dev_1.json`, etc.). See the help for more on the options it accepts.
 
 Once you've got your runs, boot `RStudio` using the `R-docker` script:
 ```sh
-cd ..
-R-docker
+/bin/R-docker
 ```
 
-This will start a Docker container running an instance of RStudio which has access to all the files in the current working directory.
+This will start a Docker container running an instance of RStudio on `localhost:8787`,which has access to all the files in the current working directory.
 
-In RStudio, open the `analysis.R` script. Change the `results` line to point at your results directory (if you're following along with our example, it should already be correct). Change the vector of names being passed to `webperf::read_lighthouse_json` to include all the configurations you gathered results for. If needed, change the `3` to be the number of runs you ran (the default for `bin/run` is three, so if you're using the defaults you can leave it alone).
+<br/>
 
-Run all the lines of `analysis.R` through line 15. Then run any of the lines that call `webperf::analyze_change` to analyze the change in the provided metric across your configurations.
+Now to analyze the results do the following:
+1. Go to `localhost:8787`
+2. In RStudio, open the `analysis.R` script.
+3. Change the `results` line to point at your results directory (if you're following along with our example, it should already be correct). 
+4. Change the vector of names being passed to `webperf::read_lighthouse_json` to include all the configurations you gathered results for. If needed, change the `3` to be the number of runs you ran (the default for `bin/run` is three, so if you're using the defaults you can leave it alone).
+5. Run all the lines of `analysis.R` through line 15, which should create data under `specs`
+6. Then run any of the lines that call `webperf::analyze_change` to analyze the change in the provided metric across your configurations.
```

</details>

## Steps Taken:
1. Git cloned `lighthouse-docker` locally
2. Used the updated REAME as a guide to install dependences, build, and run lighthouse

**Comment by andyg0808** [comment]
I _might_ have added a bunch more tools to this pull.

QA responses:
1. Should be fixed; thanks.
2. I think you might have missed the `cd` commands in the README (which are sequential and assume you're running all the steps in order). I'm not that worried, because the R code is currently targeted at interactive exploration, so if most use cases require the user to change it a bit to match how they've got stuff set up, I don't mind.
3. The `install.sh` script won't be kind on Cominor; don't bother running it with root. Basically, Ruby stores all installed packages in a global location on the machine. To access that, you need to be root. Not every Ruby setup does that, though; I tend to have a custom Ruby install in my home directories on my machines, and that works fine without root. In this case, the only gems it installs should already be present on Cominor, so we don't need to install them anyway.
4. I've dropped that script; it _was_ confusing. Now there's a Ruby library to run a container if someone needs that, or they can use the Docker container directly.
5. That's actually just weirdness of Lighthouse. I think if you specify two output formats, it'll add names to both. If you specify one, it uses exactly the name you specify. Makes sense why they might have written it that way, but it's definitely a bit weird.
6. It's not totally unreasonable. I've got to rewrite the README anyway, so we'll see what I end up with.

dev_block remains on the README rewrite.

**Comment by andyg0808** [comment]
un_dev_block :+1: README rewritten.

**Comment by cdcline** [comment]
CR 👍

**Comment by cdcline** [comment]
If we end up doing this setup a lot, might be worth making an Overlord guide.

**Comment by andyg0808** [comment]
I've changed this pull to be qa_req 0; see description for reason.

**Comment by cdcline** [comment]
CR 👍

**Review by djmetzle — APPROVED** [review]
CR :gear:

**Pull request merged**
